x-veld:
  code:

services:
  veld_step_6_analyse_vectors:
    build: ./code/analyse_vectors/
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./code/analyse_vectors/notebooks/:/veld/code/
      - ./data/vectors/:/veld/input/

