x-veld:
  chain:

services:
  veld_step_2_preprocess:
    build: ./code/bible_preprocess/
    command: python /veld/code/bible_preprocess.py
    volumes:
      - ./code/bible_preprocess/:/veld/code/
      - ./data/training_data/:/veld/input/
      - ./data/training_data/:/veld/output/
    environment:
      in_file: "bible_unprocessed.txt"
      out_file: "bible_processed.txt"

