x-veld:
  chain:
    description: "Preprocesses the bible to be compatible with word embeddings training. This chain 
      does not use a code veld but build context and code that is integrated into the chain repo 
      itself, since the preprocessing is highly specific to this kind of data and the subsequent 
      training."
    topic:
      - "ETL"
      - "NLP"
      - "Bible Studies"

services:
  veld_step_2_preprocess:
    build: ./code/bible_preprocess/
    command: python /veld/code/bible_preprocess.py
    volumes:
      - ./code/bible_preprocess/:/veld/code/
      - ./data/training_data/:/veld/input/
      - ./data/training_data/:/veld/output/
    environment:
      in_file: "bible_unprocessed.txt"
      out_file: "bible_processed.txt"

